# Generated by Django 5.2.7 on 2026-03-10 14:11

import app.models
import datetime
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('financial_year_start', models.DateField(default=app.models.get_financial_year_start)),
                ('financial_year_end', models.DateField(default=app.models.get_financial_year_end)),
                ('current_period_opened', models.BooleanField(default=True)),
                ('employee_wallets', models.JSONField(blank=True, default=list, help_text='List of employee wallet dicts for payroll: [{"wallet": "0x...", "name": "John", "salary_per_period": 5000}, ...]', null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=255)),
                ('subgroup', models.CharField(blank=True, max_length=50, null=True)),
                ('account_class', models.CharField(choices=[('ASSET', 'Asset'), ('LIABILITY', 'Liability'), ('EQUITY', 'Equity'), ('INCOME', 'Income'), ('EXPENSE', 'Expense')], max_length=20)),
                ('ifrs_account', models.CharField(choices=[('cash_and_cash_equivalents', 'Cash and Cash Equivalents'), ('trade_and_other_receivables', 'Trade and Other Receivables'), ('contract_assets', 'Contract Assets'), ('financial_assets', 'Financial Assets'), ('inventories', 'Inventories'), ('property_plant_equipment', 'Property, Plant and Equipment'), ('accumulated_depreciation_ppe', 'Accumulated Depreciation - PPE'), ('investment_property_cost', 'Investment Property (Cost)'), ('accumulated_depreciation_inv_prop', 'Accumulated Depreciation - Investment Property'), ('investment_property_fv', 'Investment Property (Fair Value)'), ('intangible_assets', 'Intangible Assets'), ('accumulated_amortisation_intangibles', 'Accumulated Amortisation - Intangibles'), ('biological_assets_cost', 'Biological Assets (Cost)'), ('biological_assets_fv', 'Biological Assets (Fair Value)'), ('investments_in_associates', 'Investments in Associates'), ('investments_in_jointly_controlled_entities', 'Investments in Jointly Controlled Entities'), ('current_tax_assets', 'Current Tax Assets'), ('deferred_tax_assets', 'Deferred Tax Assets'), ('prepayments', 'Prepayments'), ('other_current_assets', 'Other Current Assets'), ('other_non_current_assets', 'Other Non-Current Assets'), ('trade_and_other_payables', 'Trade and Other Payables'), ('contract_liabilities', 'Contract Liabilities'), ('financial_liabilities', 'Financial Liabilities'), ('current_tax_liabilities', 'Current Tax Liabilities'), ('deferred_tax_liabilities', 'Deferred Tax Liabilities'), ('provisions', 'Provisions'), ('short_term_borrowings', 'Short-Term Borrowings'), ('long_term_borrowings', 'Long-Term Borrowings'), ('lease_liabilities', 'Lease Liabilities'), ('other_current_liabilities', 'Other Current Liabilities'), ('other_non_current_liabilities', 'Other Non-Current Liabilities'), ('share_capital', 'Share Capital'), ('retained_earnings', 'Retained Earnings'), ('reserves', 'Reserves'), ('non_controlling_interest', 'Non-Controlling Interest'), ('other_equity_components', 'Other Equity Components'), ('revenue', 'Revenue'), ('gains', 'Gains'), ('share_of_profit_associates_jv', 'Share of Profit of Associates and JVs'), ('other_income', 'Other Income'), ('cost_of_sales', 'Cost of Sales'), ('operating_expenses', 'Operating Expenses'), ('depreciation_and_amortisation', 'Depreciation and Amortisation'), ('finance_costs', 'Finance Costs'), ('employee_benefits_expense', 'Employee Benefits Expense'), ('tax_expense', 'Tax Expense'), ('impairment_loss', 'Impairment Loss'), ('expenses', 'Expenses')], max_length=100)),
                ('balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='app.businessprofile')),
            ],
            options={
                'unique_together': {('business', 'code')},
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('invoice', 'Invoice (Point-in-time)'), ('customer_contract', 'Customer Contract (Over-time)'), ('revenue_recognition', 'Revenue Recognition (Unearned Drain)'), ('purchase_order', 'Purchase Order'), ('credit_note', 'Credit Note'), ('debit_note', 'Debit Note'), ('receipt', 'Receipt'), ('payment_voucher', 'Payment Voucher'), ('expense_claim', 'Expense Claim'), ('bank_statement', 'Bank Statement'), ('bill', 'Bill'), ('asset_purchase', 'Asset Purchase'), ('journal_entry', 'Journal Entry Upload'), ('short_term_borrowing', 'Loan Borrowing(short-term)'), ('long_term_borrowing', 'Loan Borrowing(long-term)'), ('tax_filing', 'Tax Filing'), ('quotation', 'Quotation'), ('delivery_note', 'Delivery Note'), ('payroll', 'Payroll Journal'), ('equity_injection', 'Equity Injection'), ('lease_agreement', 'Lease Agreement'), ('unknown', 'Unknown')], default='unknown', max_length=50)),
                ('ai_detected_type', models.CharField(blank=True, help_text='Original AI-detected document type before human review gate', max_length=50, null=True)),
                ('business_name', models.CharField(blank=True, max_length=255, null=True)),
                ('vendor', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12, null=True)),
                ('raw_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('items', models.JSONField(blank=True, default=list, null=True)),
                ('asset_class', models.CharField(blank=True, choices=[('property_plant_equipment', 'Property, Plant and Equipment'), ('intangible_assets', 'Intangible Assets'), ('investment_property_cost', 'Investment Property (Cost)')], max_length=50, null=True)),
                ('expense_category', models.CharField(blank=True, choices=[('operating_expenses', 'Operating Expenses'), ('cost_of_sales', 'Cost of Sales'), ('employee_benefits_expense', 'Employee Benefits'), ('finance_costs', 'Finance Costs'), ('depreciation_and_amortisation', 'Depreciation and Amortisation')], default='operating_expenses', max_length=100, null=True)),
                ('invoice_number', models.CharField(blank=True, max_length=100, null=True)),
                ('credit_note_number', models.CharField(blank=True, max_length=100, null=True)),
                ('debit_note_number', models.CharField(blank=True, max_length=100, null=True)),
                ('customer', models.CharField(blank=True, max_length=255, null=True)),
                ('tax', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12, null=True)),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12, null=True)),
                ('receipt_number', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_from', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_method', models.CharField(blank=True, max_length=100, null=True)),
                ('balance', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12, null=True)),
                ('invoice_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_account', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_statement', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_statement_lines', models.JSONField(blank=True, default=list, null=True)),
                ('bill_number', models.CharField(blank=True, max_length=100, null=True)),
                ('po_number', models.CharField(blank=True, max_length=100, null=True)),
                ('billed_to', models.CharField(blank=True, max_length=255, null=True)),
                ('approved_by', models.CharField(blank=True, max_length=100, null=True)),
                ('expected_delivery_date', models.CharField(blank=True, max_length=100, null=True)),
                ('expense_items', models.JSONField(blank=True, default=list, null=True)),
                ('quotation_number', models.CharField(blank=True, max_length=100, null=True)),
                ('issued_to', models.CharField(blank=True, max_length=255, null=True)),
                ('payroll_month', models.CharField(blank=True, max_length=50, null=True)),
                ('employee_salaries', models.JSONField(blank=True, default=list, null=True)),
                ('delivery_note_number', models.CharField(blank=True, max_length=100, null=True)),
                ('delivery_date', models.CharField(blank=True, max_length=100, null=True)),
                ('delivered_to', models.CharField(blank=True, max_length=255, null=True)),
                ('received_by', models.CharField(blank=True, max_length=255, null=True)),
                ('asset_description', models.CharField(blank=True, max_length=255, null=True)),
                ('asset_value', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12, null=True)),
                ('interest_rate', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=5, null=True)),
                ('equity_investor', models.CharField(blank=True, max_length=255, null=True)),
                ('equity_terms', models.CharField(blank=True, max_length=255, null=True)),
                ('loan_terms', models.CharField(blank=True, max_length=255, null=True)),
                ('loan_lender', models.CharField(blank=True, max_length=255, null=True)),
                ('blockchain_tx_hash', models.CharField(blank=True, help_text='Celo blockchain transaction hash for autonomous Celo operations (settle_bill, payroll, yield)', max_length=255, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='app.businessprofile')),
            ],
        ),
        migrations.CreateModel(
            name='FinancialPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_closed', models.BooleanField(default=False)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='app.businessprofile')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='FixedAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('asset_class', models.CharField(choices=[('property_plant_equipment', 'Property, Plant and Equipment'), ('intangible_assets', 'Intangible Assets'), ('investment_property_cost', 'Investment Property (Cost)'), ('investment_property_fv', 'Investment Property (Fair Value)'), ('biological_assets_fv', 'Biological Assets (Fair Value)')], max_length=50)),
                ('measurement_model', models.CharField(choices=[('cost', 'Cost Model (Depreciates)'), ('fair_value', 'Fair Value Model (Appreciates/Devaluates)')], default='cost', max_length=20)),
                ('purchase_cost', models.DecimalField(decimal_places=2, max_digits=14)),
                ('accumulated_depreciation', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('useful_life_years', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=5)),
                ('residual_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('depreciation_method', models.CharField(choices=[('straight_line', 'Straight Line'), ('reducing_balance', 'Reducing Balance')], default='straight_line', max_length=50)),
                ('current_fair_value', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('accumulated_fair_value_adjustment', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('date_acquired', models.DateField(default=datetime.date.today)),
                ('is_active', models.BooleanField(default=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fixed_assets', to='app.businessprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('description', models.TextField()),
                ('is_manual_adjustment', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft (AI Proposed)'), ('PENDING', 'Anomaly - Pending Human Review'), ('POSTED', 'Auto-Posted (Cleared IFRS Rules)'), ('REJECTED', 'Rejected by Deterministic Accounting Gate')], default='DRAFT', max_length=20)),
                ('blockchain_tx_hash', models.CharField(blank=True, help_text='Celo blockchain transaction hash for Web3 operations', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='app.businessprofile')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='app.document')),
                ('period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='app.financialperiod')),
            ],
        ),
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('debit', 'Debit'), ('credit', 'Credit')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_entries', to='app.account')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='app.transaction')),
            ],
        ),
        migrations.AddField(
            model_name='document',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='app.transaction'),
        ),
    ]
