# Generated by Django 5.2.7 on 2026-03-14 15:05

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='primary_network',
            field=models.CharField(default='celo-sepolia', help_text='The default EVM chain for this business', max_length=50),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='private_key_encrypted',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='public_key',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='wallet_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='vendor_wallet',
            field=models.CharField(blank=True, help_text='Web3 wallet address extracted for the vendor', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='blockchain_tx_hash',
            field=models.CharField(blank=True, help_text='Web3 blockchain transaction hash for autonomous Web3 operations (settle_bill, payroll, yield)', max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Shareholder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('wallet_address', models.CharField(blank=True, help_text='Web3 wallet for dividend airdrops', max_length=255, null=True)),
                ('total_investment', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shareholders', to='app.businessprofile')),
            ],
            options={
                'unique_together': {('business', 'name')},
            },
        ),
    ]
