# Generated by Django 5.2.7 on 2026-03-19 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_businessprofile_primary_network_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessprofile',
            name='private_key_encrypted',
        ),
        migrations.AddField(
            model_name='document',
            name='unsigned_payload',
            field=models.JSONField(blank=True, help_text='Raw intent data queued for OpenClaw to sign locally', null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft (AI Proposed)'), ('PENDING', 'Anomaly - Pending Human Review'), ('PENDING_SIGNATURE', 'Awaiting Local OpenClaw Signature'), ('POSTED', 'Auto-Posted (Cleared IFRS Rules)'), ('REJECTED', 'Rejected by Deterministic Accounting Gate')], default='DRAFT', max_length=20),
        ),
    ]
